databases:
  - name: pl0xdb
    plan: free
    databaseName: pl0x
    user: pl0x

services:
  - type: web
    plan: free
    name: pl0x
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn pplox_web.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pl0xdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4